package:
  name: climate4r
  version: 1.0

#build:
#  rpaths:
#    - lib/R/lib/
#    - lib/
#    - jre/lib/amd64/server/

requirements:
  build:
    - r-base==3.6.1
    - openjdk
    - r-rjava
    - r-udunits2
    - r-ncdf4
    - xorg-libxt
    - udunits2
  run:
    - r-base==3.6.1
    - openjdk
    - r-rjava
    - r-udunits2
    - r-ncdf4
    - xorg-libxt
    - udunits2

about:
  home: https://github.com/SantanderMetGroup/climate4R
