package:
  name: climate4r
  version: 0.2

requirements:
  build:
    - r=3.5.1
    - r-rjava
    - r-devtools
  run:
    - r=3.5.1
    - r-rjava
    - r-devtools

about:
  home: https://github.com/SantanderMetGroup/climate4R
